services:
  db:
    image: postgres:14.13-alpine3.20
    container_name: postgres_db
    restart: on-failure
    environment:
      POSTGRES_DB: db_properties
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - csp-network

volumes:
  db_data:

networks:
  csp-network: